"""Golden-vector parity tests: PyTorch mirror vs canonical Rust output.

The vectors in ``shared/golden_vectors.json`` are generated by the Rust
canonical implementation (``runtime-core/src/bin/generate_golden_vectors.rs``).
These tests replay them through the Python mirrors and fail on any divergence.
If you change the Rust math, regenerate the file and update the mirrors in the
same commit — otherwise these tests (and their frontend counterparts) fail.

Authority: docs/adr/0001-rust-first-parity.md
"""

from __future__ import annotations

import cmath
import json
import math
import os
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GOLDEN_PATH = os.path.join(REPO_ROOT, "shared", "golden_vectors.json")


@pytest.fixture(scope="module")
def golden() -> dict:
    if not os.path.exists(GOLDEN_PATH):
        pytest.fail(
            f"Golden vectors missing at {GOLDEN_PATH}. Regenerate with: "
            "cargo run --release -p runtime_core --bin generate_golden_vectors"
        )
    with open(GOLDEN_PATH) as f:
        return json.load(f)


def _carrier_reference(theta: float, s: float) -> complex:
    """Independent closed form: c = μ/2 − μ²/4 with μ = s·e^{iθ}."""
    mu = s * cmath.exp(1j * theta)
    return mu / 2 - mu**2 / 4


class TestCarrierGolden:
    def test_carrier_matches_golden(self, golden):
        for case in golden["carrier_cases"]:
            expected = _carrier_reference(case["theta"], case["s"])
            assert abs(expected.real - case["c_re"]) < 1e-9
            assert abs(expected.imag - case["c_im"]) < 1e-9


class TestMirrorGolden:
    """The PyTorch mirror must reproduce Rust synthesize() exactly."""

    def test_synthesize_c_matches_golden(self, golden):
        import torch

        from src.cspace_proxies import synthesize_c

        max_err = 0.0
        for case in golden["orbit_cases"]:
            pt_c = synthesize_c(
                s_target=torch.tensor([case["s"]]),
                alpha=torch.tensor([case["alpha"]]),
                band_gates=torch.tensor([case["band_gates"]], dtype=torch.float32),
                thetas=torch.tensor([case["theta"]]),
                k_residuals=len(case["band_gates"]),
                residual_cap=0.5,
                phases=None,  # mirror derives phases from shared seed source
            )
            # The golden cases use per-case seeds; the mirror's phase source is
            # keyed by DEFAULT_ORBIT_SEED. To compare apples-to-apples we pass
            # the phases the Rust generator used — recover them via runtime_core.
            import runtime_core

            phases = runtime_core.residual_phases_for_seed_py(case["seed"], len(case["band_gates"]))
            pt_c = synthesize_c(
                s_target=torch.tensor([case["s"]]),
                alpha=torch.tensor([case["alpha"]]),
                band_gates=torch.tensor([case["band_gates"]], dtype=torch.float32),
                thetas=torch.tensor([case["theta"]]),
                k_residuals=len(case["band_gates"]),
                residual_cap=0.5,
                phases=phases,
            )
            err = max(
                abs(pt_c[0].real.item() - case["c_re"]),
                abs(pt_c[0].imag.item() - case["c_im"]),
            )
            max_err = max(max_err, err)
        assert max_err < 1e-5, f"mirror diverged from golden: max_err={max_err}"


class TestOrbitControllerMirrorGolden:
    """The differentiable OrbitController mirror vs the Rust binding.

    This is THE parity contract for training: if this fails, the trainer
    supervises physics the browser does not execute.
    """

    def test_orbit_mirror_matches_rust(self):
        import numpy as np
        import runtime_core
        import torch

        from src.cspace_proxies import orbit_controller_sequence

        rng = np.random.RandomState(0)
        n_steps = 120
        s_vals = torch.tensor(
            np.clip(rng.uniform(0.2, 3.0, n_steps), 0.2, 3.0), dtype=torch.float32
        )
        a_vals = torch.tensor(rng.uniform(0.0, 1.0, n_steps), dtype=torch.float32)
        gates = torch.tensor(rng.uniform(0.0, 1.0, (n_steps, 6)), dtype=torch.float32)
        seg = torch.zeros(n_steps, dtype=torch.int64)

        c = runtime_core.OrbitController(float(s_vals[0]), float(a_vals[0]), 1.0)
        rust_re = rust_im = 0.0
        for i in range(n_steps):
            c.apply_controls(float(s_vals[i]), float(a_vals[i]))
            rust_re, rust_im = c.step(1.0 / 60.0, gates[i].tolist())

        pt_c = orbit_controller_sequence(
            s_target=s_vals,
            alpha=a_vals,
            omega=1.0,
            band_gates=gates,
            segment_ids=seg,
        )
        err = max(
            abs(rust_re - pt_c[-1].real.item()),
            abs(rust_im - pt_c[-1].imag.item()),
        )
        assert err < 1e-5, (
            f"OrbitController mirror diverged from Rust: err={err} "
            "(trainer would supervise wrong physics)"
        )


class TestProximityGolden:
    def test_proximity_matches_golden(self, golden):
        import numpy as np
        import torch

        from src.cspace_proxies import cardioid_proximity

        points = [complex(c["c_re"], c["c_im"]) for c in golden["proximity_cases"]]
        c_tensor = (
            torch.tensor([p.real for p in points], dtype=torch.float32)
            + 1j * torch.tensor([p.imag for p in points], dtype=torch.float32)
        ).to(torch.complex64)
        pt_vals = cardioid_proximity(c_tensor).tolist()
        for pv, case in zip(pt_vals, golden["proximity_cases"]):
            assert abs(pv - case["proximity"]) < 1e-5
