"""Golden-vector parity tests: PyTorch mirror vs canonical Rust output.

The vectors in ``shared/golden_vectors.json`` are generated by the Rust
canonical implementation (``runtime-core/src/bin/generate_golden_vectors.rs``).
These tests replay them through the Python mirrors and fail on any divergence.
If you change the Rust math, regenerate the file and update the mirrors in the
same commit — otherwise these tests (and their frontend counterparts) fail.

Authority: docs/adr/0001-rust-first-parity.md
"""

from __future__ import annotations

import cmath
import json
import math
import os
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GOLDEN_PATH = os.path.join(REPO_ROOT, "shared", "golden_vectors.json")


@pytest.fixture(scope="module")
def golden() -> dict:
    if not os.path.exists(GOLDEN_PATH):
        pytest.fail(
            f"Golden vectors missing at {GOLDEN_PATH}. Regenerate with: "
            "cargo run --release -p runtime_core --bin generate_golden_vectors"
        )
    with open(GOLDEN_PATH) as f:
        return json.load(f)


def _carrier_reference(theta: float, s: float) -> complex:
    """Independent closed form: c = μ/2 − μ²/4 with μ = s·e^{iθ}."""
    mu = s * cmath.exp(1j * theta)
    return mu / 2 - mu**2 / 4


class TestCarrierGolden:
    def test_carrier_matches_golden(self, golden):
        for case in golden["carrier_cases"]:
            expected = _carrier_reference(case["theta"], case["s"])
            assert abs(expected.real - case["c_re"]) < 1e-9
            assert abs(expected.imag - case["c_im"]) < 1e-9


class TestMirrorGolden:
    """The PyTorch mirror must reproduce Rust synthesize() exactly."""

    def test_synthesize_c_matches_golden(self, golden):
        import torch

        from src.cspace_proxies import synthesize_c

        max_err = 0.0
        for case in golden["orbit_cases"]:
            pt_c = synthesize_c(
                s_target=torch.tensor([case["s"]]),
                alpha=torch.tensor([case["alpha"]]),
                band_gates=torch.tensor([case["band_gates"]], dtype=torch.float32),
                thetas=torch.tensor([case["theta"]]),
                k_residuals=len(case["band_gates"]),
                residual_cap=0.5,
                phases=None,  # mirror derives phases from shared seed source
            )
            # The golden cases use per-case seeds; the mirror's phase source is
            # keyed by DEFAULT_ORBIT_SEED. To compare apples-to-apples we pass
            # the phases the Rust generator used — recover them via runtime_core.
            import runtime_core

            phases = runtime_core.residual_phases_for_seed_py(case["seed"], len(case["band_gates"]))
            pt_c = synthesize_c(
                s_target=torch.tensor([case["s"]]),
                alpha=torch.tensor([case["alpha"]]),
                band_gates=torch.tensor([case["band_gates"]], dtype=torch.float32),
                thetas=torch.tensor([case["theta"]]),
                k_residuals=len(case["band_gates"]),
                residual_cap=0.5,
                phases=phases,
            )
            err = max(
                abs(pt_c[0].real.item() - case["c_re"]),
                abs(pt_c[0].imag.item() - case["c_im"]),
            )
            max_err = max(max_err, err)
        assert max_err < 1e-5, f"mirror diverged from golden: max_err={max_err}"


class TestPlayerGolden:
    """PlayerState momentum integrator trajectories."""

    def test_player_step_matches_golden(self, golden):
        import runtime_core

        for case in golden["player_step_cases"]:
            p = runtime_core.PlayerState(1, 0, case["s0"], case["alpha0"])
            p.set_d_star(case["d_star"])
            p.set_max_step(case["max_step"])
            p.set_level(case["level"])
            c_re = c_im = None
            for ctrl in case["controls"]:
                s, alpha, omega_scale = ctrl
                p.apply_controls(s, alpha, omega_scale)
                c_re, c_im = p.step(case["dt"], case["h"], case["band_gates"])
            err = max(abs(c_re - case["c_re"]), abs(c_im - case["c_im"]))
            assert err < 1e-6, (
                f"PlayerState trajectory diverged from golden: err={err} "
                "(did Rust math change without regenerating golden_vectors.json?)"
            )

    def test_player_mirror_matches_golden(self, golden):
        """The differentiable PyTorch mirror must reproduce Rust trajectories.

        This is THE parity contract for training: if this fails, the trainer
        supervises physics the browser does not execute.
        """
        import torch

        from src.cspace_proxies import player_step_sequence

        max_err = 0.0
        for case in golden["player_step_cases"]:
            controls = case["controls"]
            n = len(controls)
            s_t = torch.tensor([c[0] for c in controls])
            a_t = torch.tensor([c[1] for c in controls])
            w_t = torch.tensor([c[2] for c in controls])
            gates = (
                torch.tensor([case["band_gates"]], dtype=torch.float32)
                .repeat(n, 1)
            )
            seg = torch.zeros(n, dtype=torch.int64)

            # Start on the boundary at (s0, alpha0) like PlayerState::new.
            theta0 = case["alpha0"] * 2.0 * math.pi
            mu0 = case["s0"] * cmath.exp(1j * theta0)
            c0_complex = mu0 / 2 - mu0**2 / 4

            pt_c = player_step_sequence(
                s_target=s_t,
                alpha=a_t,
                omega_scale=w_t,
                band_gates=gates,
                segment_ids=seg,
                dt=case["dt"],
                c0=(c0_complex.real, c0_complex.imag),
            )
            err = max(
                abs(pt_c[-1].real.item() - case["c_re"]),
                abs(pt_c[-1].imag.item() - case["c_im"]),
            )
            max_err = max(max_err, err)
        assert max_err < 1e-5, (
            f"PlayerState mirror diverged from golden: max_err={max_err} "
            "(trainer would supervise wrong physics)"
        )


class TestProximityGolden:
    def test_proximity_matches_golden(self, golden):
        import numpy as np
        import torch

        from src.cspace_proxies import cardioid_proximity

        points = [complex(c["c_re"], c["c_im"]) for c in golden["proximity_cases"]]
        c_tensor = (
            torch.tensor([p.real for p in points], dtype=torch.float32)
            + 1j * torch.tensor([p.imag for p in points], dtype=torch.float32)
        ).to(torch.complex64)
        pt_vals = cardioid_proximity(c_tensor).tolist()
        for pv, case in zip(pt_vals, golden["proximity_cases"]):
            assert abs(pv - case["proximity"]) < 1e-5
