"""Minimal stubs for src.runtime_core_bridge used in tests."""

from __future__ import annotations

from typing import Any, Optional

SAMPLE_RATE: int
HOP_LENGTH: int
N_FFT: int
WINDOW_FRAMES: int
MINIMAP_MIP_LEVELS: int
MINIMAP_PATCH_K: int
STEP_CONTEXT_LEN: int

def make_feature_extractor(
    include_delta: bool = ..., include_delta_delta: bool = ...
) -> Any: ...
def make_orbit_state(*args: Any, **kwargs: Any) -> Any: ...
def make_residual_params(*args: Any, **kwargs: Any) -> Any: ...
def make_step_controller() -> Any: ...
def step_mip_for_delta(delta_real: float, delta_imag: float) -> int: ...
def synthesize(state: Any, residual_params: Optional[Any] = None) -> Any: ...
