/**
 * Golden-vector parity tests: TypeScript mock vs canonical Rust output.
 *
 * The vectors in `shared/golden_vectors.json` are generated by the Rust
 * canonical implementation (`runtime-core/src/bin/generate_golden_vectors.rs`).
 * The TS mock (orbitSynthesizer.mock.ts) must reproduce them within tolerance.
 * If you change the Rust math, regenerate the file and update every mirror in
 * the same commit — otherwise these tests (and their backend counterparts)
 * fail.
 *
 * Authority: docs/adr/0001-rust-first-parity.md
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, it, expect, beforeAll } from 'vitest';
import {
  initOrbitSynth,
  OrbitSynthesizer,
} from '../orbitSynthesizer';

interface CarrierCase {
  theta: number;
  s: number;
  c_re: number;
  c_im: number;
}
interface PlayerStepCase {
  s0: number;
  alpha0: number;
  dt: number;
  h: number;
  d_star: number;
  max_step: number;
  level: number;
  controls: [number, number, number][];
  band_gates: number[] | null;
  c_re: number;
  c_im: number;
}
interface GoldenVectors {
  carrier_cases: CarrierCase[];
  player_step_cases: PlayerStepCase[];
}

let golden: GoldenVectors;

beforeAll(async () => {
  (globalThis as any).__vitest = true;
  await initOrbitSynth();
  // Repo root is two levels up from frontend/ (vitest __dirname = src/lib/__tests__).
  const goldenPath = resolve(__dirname, '../../../../shared/golden_vectors.json');
  golden = JSON.parse(readFileSync(goldenPath, 'utf-8'));
});

describe('Golden-vector parity (TS mock vs Rust canonical)', () => {
  it('carrier cases match the closed form recorded by Rust', () => {
    // The mock's lobePoint must agree with the golden carrier values.
    for (const c of golden.carrier_cases) {
      const synth = new OrbitSynthesizer(6, { s: c.s, alpha: c.theta / (2 * Math.PI) });
      expect(synth.cRe).toBeCloseTo(c.c_re, 9);
      expect(synth.cIm).toBeCloseTo(c.c_im, 9);
    }
  });

  it('PlayerState momentum trajectories match Rust step-for-step', () => {
    for (const tc of golden.player_step_cases) {
      const synth = new OrbitSynthesizer(6, { s: tc.s0, alpha: tc.alpha0 });
      if (tc.d_star !== undefined && typeof (synth as any).setDStar === 'function') {
        (synth as any).setDStar(tc.d_star);
      }
      let last = { real: synth.cRe, imag: synth.cIm };
      for (const [s, alpha, omega] of tc.controls) {
        synth.applyControls({ sTarget: s, alpha, omegaScale: omega, bandGates: [] });
        last = synth.step(tc.dt, tc.band_gates ?? [], tc.h);
      }
      expect(last.real).toBeCloseTo(tc.c_re, 6);
      expect(last.imag).toBeCloseTo(tc.c_im, 6);
    }
  });
});
