declare module '/wasm/orbit_synth_wasm.js' {
  export default function init(): Promise<void>;

  // Re-export the wasm-orbit generated types so consumers in this module
  // see the Rust-authored interface shape (issue #93 strict-version
  // review). The `types` field in tsconfig points at
  // `../wasm-orbit/pkg/orbit_synth_wasm.d.ts`, which is regenerated by
  // `wasm-pack build --target bundler` from
  // `wasm-orbit/src/lib.rs` (see `typescript_custom_section` there).
  export type { AnalysisTick, TimebaseDiagnostics } from 'orbit-synth-wasm';

  export class AnalysisTimebase {
    constructor();
    ingest(samples: Float32Array, sourceSampleRate: number, sourceStartFrame: bigint): AnalysisTick[];
    flush(): AnalysisTick[];
    reset(): void;
    diagnostics(): TimebaseDiagnostics;
    free(): void;
  }

  export class OrbitState {
    constructor(
      lobe: number,
      sub_lobe: number,
      theta: number,
      omega: number,
      s: number,
      alpha: number,
      k_residuals: number,
      residual_omega_scale: number,
      seed?: bigint | null
    );
    lobe: number;
    sub_lobe: number;
    theta: number;
    omega: number;
    s: number;
    alpha: number;
    set_lobe(v: number): void;
    set_sub_lobe(v: number): void;
    set_s(v: number): void;
    set_alpha(v: number): void;
    set_omega(v: number): void;
    advance(dt: number): void;
  }

  export class ResidualParams {
    constructor(k_residuals: number, residual_cap: number, radius_scale: number);
  }

  export class PlayerState {
    constructor(lobe: number, sub_lobe: number, s: number, alpha: number);
    c_re: number;
    c_im: number;
    speed: number;
    set_level(v: number): void;
    set_d_star(v: number): void;
    set_max_step(v: number): void;
    apply_controls(s: number, alpha: number, omega_scale: number): void;
    set_lobe(lobe: number, sub_lobe: number): void;
    step(
      dt: number,
      h: number,
      band_gates?: Float64Array | null
    ): { real: number; imag: number };
  }

  /** May-proven orbit controller (restored baseline) with opt-in refinements. */
  export class OrbitController {
    constructor(s: number, alpha: number, omega: number);
    theta: number;
    apply_controls(s: number, alpha: number): void;
    set_momentum(on: boolean): void;
    set_drag(drag: number): void;
    set_shore_bias(on: boolean): void;
    set_d_star(d_star: number): void;
    set_max_step(max_step: number): void;
    step(
      dt: number,
      band_gates?: Float64Array | null
    ): { real: number; imag: number };
  }

  export function step(
    state: OrbitState,
    dt: number,
    residual_params: ResidualParams,
    band_gates?: Float64Array | null
  ): { real: number; imag: number };

  export function synthesize(
    state: OrbitState,
    residual_params: ResidualParams,
    band_gates?: Float64Array | null
  ): { real: number; imag: number };

  export function constants(): {
    sample_rate: number;
    hop_length: number;
    n_fft: number;
    window_frames: number;
    default_k_residuals: number;
    default_residual_cap: number;
    default_residual_omega_scale: number;
    default_base_omega: number;
    default_orbit_seed: number;
  };
}
