"""
Visualize the generated distance field as an image.
Requires matplotlib for visualization.
"""

import sys
import argparse
from pathlib import Path

import numpy as np


def visualize_distance_field(npy_path: Path, save_path: Path = None):
    """
    Load and visualize a distance field.
    
    Args:
        npy_path: Path to the .npy distance field file
        save_path: Optional path to save the visualization as an image
    """
    # Load the distance field
    distance = np.load(npy_path)
    
    print(f"Loaded distance field from {npy_path}")
    print(f"  Shape: {distance.shape}")
    print(f"  Range: [{distance.min():.4f}, {distance.max():.4f}]")
    
    # Try to import matplotlib
    try:
        import matplotlib.pyplot as plt
        import matplotlib.colors as mcolors
    except ImportError:
        print("\nError: matplotlib is required for visualization")
        print("Install with: pip install matplotlib")
        return
    
    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    # Plot 1: Distance field with diverging colormap
    im1 = ax1.imshow(distance, cmap='RdBu_r', origin='lower')
    ax1.set_title('Signed Distance Field\n(red=inside, blue=outside)')
    ax1.set_xlabel('X')
    ax1.set_ylabel('Y')
    plt.colorbar(im1, ax=ax1, label='Signed Distance')
    
    # Plot 2: Binary mask (inside/outside)
    mask = distance < 0  # Inside the set
    ax2.imshow(mask, cmap='gray', origin='lower')
    ax2.set_title('Mandelbrot Set Mask\n(white=inside)')
    ax2.set_xlabel('X')
    ax2.set_ylabel('Y')
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"\nVisualization saved to {save_path}")
    else:
        print("\nDisplaying visualization (close window to continue)...")
        plt.show()


def main():
    parser = argparse.ArgumentParser(
        description="Visualize a distance field generated by build_distance_field.py"
    )
    parser.add_argument(
        "npy_path",
        type=Path,
        help="Path to the .npy distance field file"
    )
    parser.add_argument(
        "--save",
        type=Path,
        help="Save visualization to image file instead of displaying"
    )
    
    args = parser.parse_args()
    
    if not args.npy_path.exists():
        print(f"Error: File not found: {args.npy_path}")
        sys.exit(1)
    
    visualize_distance_field(args.npy_path, args.save)


if __name__ == "__main__":
    main()
