/**
 * Authoritative sample-clock audio timebase (issue #91) — TypeScript seam.
 *
 * The deterministic transport/timing/scheduling/resampling math lives in
 * `runtime-core/src/timebase.rs` (Rust) and is consumed here through the
 * wasm-orbit `AnalysisTimebase` binding. Per ADR 0001 there is deliberately
 * NO TypeScript mirror of the resampler, hop scheduler, or sample
 * accounting — this module is a thin adapter that delegates to the wasm
 * instance.
 *
 * Architecture (issue #91):
 *
 *   file or microphone source
 *           ↓
 *   Web Audio sample clock (AudioWorklet render quanta)
 *           ↓
 *   exactly-once non-overlapping PCM transport (monotonic source position)
 *           ↓
 *   continuous canonical 48 kHz stream (Rust stateful streaming resampler)
 *           ↓
 *   exact 1024-sample hop scheduler (Rust)
 *           ↓
 *   runtime-core FeatureExtractor via WASM
 *           ↓
 *   AnalysisTick { features, sampleIndex, timeSeconds, dtSeconds, streamEpoch }
 *           ↓
 *   audio-driven consumers (model inference / future CycleBank)
 *
 * `AnalysisTick` and `TimebaseDiagnostics` are GENERATED by wasm-pack from
 * the `typescript_custom_section` block in `wasm-orbit/src/lib.rs`. This
 * file does NOT redeclare them — Rust owns the wire-format shape and the
 * Python trainer reads the same record via its camelCase keys
 * (`sampleIndex`/`timeSeconds`/...) from the matching PyO3 serializer
 * (cross-surface parity, issue #93 strict-version review).
 *
 * Canonical constants (sample rate, hop length) are NOT redeclared here:
 * read them from the wasm binding via getWasmConstants() (orbitSynthesizer)
 * + getRuntimeConstants() (canonicalFeatures) — runtime-core is the only
 * authority.
 */

import type { AnalysisTick, TimebaseDiagnostics } from 'orbit-synth-wasm';

/** A block of PCM observed from the Web Audio sample clock. */
export interface PcmBlock {
  /** Non-overlapping PCM samples at the source sample rate. */
  samples: Float32Array;
  /** Source sample rate (e.g. 44100, 48000). */
  sourceSampleRate: number;
  /**
   * Position of `samples[0]` on the source sample clock, in source frames
   * since the stream started. Must be monotonically non-decreasing.
   */
  sourceStartFrame: number;
}

// Re-export the Rust-owned types so existing consumers
// (`import { AnalysisTick, TimebaseDiagnostics } from './analysisTimebase'`)
// keep working without change. The actual type definitions live in
// `wasm-orbit/src/lib.rs` and are emitted into the generated
// `orbit-synth-wasm.d.ts` (see `typescript_custom_section` there).
export type { AnalysisTick, TimebaseDiagnostics };

/** Shape of the wasm-orbit AnalysisTimebase binding (subset). */
export interface WasmAnalysisTimebase {
  ingest(
    samples: Float32Array,
    sourceSampleRate: number,
    sourceStartFrame: bigint
  ): AnalysisTick[];
  flush(): AnalysisTick[];
  reset(): void;
  diagnostics(): TimebaseDiagnostics;
  free(): void;
}

/**
 * Thin wrapper over the wasm-orbit `AnalysisTimebase`. Owns no timing math;
 * every operation delegates to the Rust instance so the browser and any
 * future Rust consumer share one implementation.
 */
export class AnalysisTimebase {
  private inner: WasmAnalysisTimebase;

  /** Wrap a live wasm binding instance (constructed by the caller). */
  constructor(wasmInstance: WasmAnalysisTimebase) {
    this.inner = wasmInstance;
  }

  /**
   * Ingest one non-overlapping PCM block. Throws on non-monotonic source
   * position (a transport bug, not a stream discontinuity — those are
   * declared via `reset()`). Returns the ticks whose hop boundaries
   * completed within this block (zero or more).
   */
  ingest(block: PcmBlock): AnalysisTick[] {
    return (
      this.inner.ingest(
        block.samples,
        block.sourceSampleRate,
        BigInt(block.sourceStartFrame)
      ) ?? []
    );
  }

  /** Flush end-of-stream (recovers the deferred final sample/tick). */
  flush(): AnalysisTick[] {
    return this.inner.flush() ?? [];
  }

  /** Declare a stream discontinuity (start/stop/source replacement). */
  reset(): void {
    this.inner.reset();
  }

  /** Diagnostic snapshot for verifying the clock manually. */
  get diagnostics(): TimebaseDiagnostics {
    return this.inner.diagnostics();
  }

  /** Release the underlying wasm instance. */
  dispose(): void {
    this.inner.free();
  }
}
